module.exports = {
    "getting_energy": `Energy is calculated based on the number of batteries and elixirs. The base energy for the full interval is 50 times the number of batteries. The Elixir increases the bonus by 10% for each level. Energy is charged in proportion to the elapsed time since the last feeding, but not more than one full interval.`,
    "how_to_reward": "💎⁉ How to reward?",
"how_to_reward_text": `1. Send any amount of $HONEY to the bear's address (the game address that is written in the main menu)
2. Enter the command:
<code>/reward 30 10000</code>
Where 30 is the reward amount,
10000 is the minimum number of power (optional: 0 by default).`,
"rewards_sended": "Rewards have been sent!",
"add_rewards_error": "Error sending rewards",    
"main_menu": "🏠 Main menu",
"check_stats": "💠 Strengthen",
"for_rewards": "💎 For awards",
"for_rewards_not_register": `The wallet is not registered to receive rewards. Please send it (starting from 0x) or click on the registration button for the game wallet (not recommended: rewards may be rejected due to the unnaturalness of the wallet).
This can be your wallet in Bera chain, which is available in Metamask, Trust wallet, Rabbit, or another wallet.`,
"registerWithgameWallet": "Register a gaming wallet",
"for_rewards_text": `Rewards are based on a system of points (they are called strength), which are calculated using a special formula:

Power = energy * batteries + (energy * batteries * elixir%)

Where:
- "energy" — this is the amount of user's energy.
- "batteries" — the number of batteries that increase energy.
- "Elixir%" is a percentage power bonus based on the elixir.`,
"for_rewards_example": "An example for your bear",
"power_reyting": "🏆💎Strength rating",
"gettingData": "Data is being collected. Please wait.",
"rewards_top_list_info": "wallet address for rewards - fixed strength (% of all fixed strength of bears)",
"power_updated": "Congratulations! The bear has become stronger! Wait for the rewards.",
"error_checking_power": "Gain error",
"rewards_ranking": "Strength rating",
"now_power": "The recorded power (update to update)",
"wallet_registered": "The wallet is registered. Now you can strengthen your bear to receive rewards.",
"wallet_already_registered": "The wallet has already been registered.",
"no_approved_honey": "There are no approved $HONEY tokens to transfer to the smart contract.",
"no_eligible_users": "There are no users suitable for the criteria.",
"view_tasks": "👀 View Tasks",
    "feed": "🍯 Feed",
    "confirm_action": "Do you really want to",
    "energy_cost": "You will waste energy",
    "confirm_button": "Confirm!",
    "buy_battery": "🔋 Buy a battery",
    "buy_elixir": "💊 Buy elixir",
    "top_leaders": "🏆 Top leaders",
    "migrate": "🛣 Migrate",
    "your_bera_address": "Your bear's address",
    "referral_link": "Referral link",
    "energy": "Energy",
    "number_of_batteries": "Number of batteries",
    "elixir": "Elixir",
    "time_until_next_feeding": "Time until next feeding",
    "seconds": "seconds",
    "feed_now": "You can feed now!",
    "accumulated_energy": "Accumulated energy",
    "about_berachain": "About Berachain",
    "faucet": "Faucet",
    "explorer": "Explorer",
    "about_bot": "Welcome to the game where you feed the bear, getting rewards (energy)! By buying batteries for energy, you increase the time between feedings, and by buying elixirs for energy, you increase the amount of reward (these purchases without spending real money)!",
    "user_ranking": "User rating by Bear energy",
    "top_list_info": "№ The bear's address is the current energy (% of the current energy of all players)",
    "leaders_file": "Leaders file",
    "insufficient_balance_for_add_task": "Insufficient balance. You need 1 BERA to add a task.",
    "task_added": "Task added successfully!",
    "please_provide_details_for_add_task": "Please provide task details in the format: Title | Description | Action",
    "invalid_add_task_format": "Invalid format. Please provide details in the format: Title | Description | Action",
    "action": "Action",
    "here_are_tasks": "Choose a task, complete it and earn +10 energy for your bear!",
    "i_did": "I did",
    "previous": "Previous",
    "next": "Next",
    "add_task": "➕ Add task",
    "error_occurred": "An error occurred",
    "balance_replenished": "Click the button again - the balance has already been replenished.",
    "error_fetching_ranking": "Error fetching user ranking.",
    "feed_bear_prompt": "Your bear is hungry! Click on the 'Main menu' button, and then '🍯 Feed'.",
    "leaders": "Leaders",
    "error_adding_task": "Error adding task.",
    "error_fetching_leaderboard": "Error fetching leaderboard.",
    "please_start_bot": "You need to start the bot first by using /start command.",
    "data_migration_successful": "Data migration successful!",
    "bear_fed": "Bear has been fed!",
    "battery_purchased": "The battery is purchased!",
    "elixir_purchased": "Elixir purchased!",
    "task_marked_complete": "Task marked as completed!",
    "error_during": "Error during",
        "error_cannot_estimate_gas": "Unable to estimate gas. Please try again later or set a manual gas limit.",
        "error_bera_not_hungry": "The Bera isn't ready to eat yet. Please wait before feeding.",
        "error_data_already_migrated": "Your data has already been migrated.",
        "error_insufficient_energy_boost": "Not enough energy to perform a boost.",
        "error_max_elixir": "Your elixir has reached its maximum level.",
        "error_max_battery": "Your battery has reached its maximum level.",
        "error_insufficient_energy_buy_elixir": "Not enough energy to buy elixir.",
        "error_insufficient_energy_boost_time": "Not enough energy to boost time.",
        "error_failed_to_send_ether": "Transaction failed. Unable to send Ether.",
        "error_page_greater_than_zero": "Page number must be greater than zero.",
        "error_task_out_of_range": "The specified task ID is out of range.",
        "error_task_already_completed": "This task has already been completed.",
        "error_insufficient_funds": "You have insufficient funds in your wallet.",
"invalid_wallet_address": "Invalid wallet address"
};